core/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from .views import (HomeListView, GaleriaListView, AutorListView, AutorDetailView, SugestaoListView, ContatoTemplateView,
                    ComprarTemplateView, VenderTemplateView, GalleryRoomListView)

urlpatterns = patterns('',
    url(r'^$', HomeListView.as_view(), name='home'),
    url(r'^gallery/$', GalleryRoomListView.as_view(), name='gallery'),
    url(r'^galeria/$', GaleriaListView.as_view(), name='galeria'),
    url(r'^autores/$', AutorListView.as_view(), name='autores'),
    url(r'^autor/(?P<pk>\d+)/$', AutorDetailView.as_view(), name='autor'),
    url(r'^sugestoes/$', SugestaoListView.as_view(), name='sugestoes'),
    url(r'^vender/$', VenderTemplateView.as_view(), name='vender'),
    url(r'^comprar/$', ComprarTemplateView.as_view(), name='comprar'),
    url(r'^contato/$', ContatoTemplateView.as_view(), name='contato'),
)

pistalo/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pistalo.views.home', name='home'),
    # url(r'^pistalo/', include('pistalo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # App
    url(r'^', include('core.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

core/models.py
# coding: utf-8
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from .managers import AtivoManager


class Autor(models.Model):
    ordenacao = models.PositiveSmallIntegerField(u'Ordenação', default=0)
    nome = models.CharField(max_length=120)
    desc = models.TextField(u'Descrição', blank=True)
    imagem = models.ImageField(upload_to='galeria', null=True, blank=True)
    thumb = ImageSpecField(source='imagem', processors=[ResizeToFill(160, 160)], format='JPEG', options={'quality': 60})
    ativo = models.BooleanField(default=False)

    data_criacao = models.DateTimeField(
        verbose_name=u'Data de criação',
        auto_now_add=True,
        editable=True
    )
    data_atualizacao = models.DateTimeField(
        verbose_name=u'Data de atualização',
        auto_now=True,
        editable=True
    )

    objects = AtivoManager()

    class Meta:
        ordering = ['ordenacao', 'nome']
        verbose_name_plural = u'Autores'

    @models.permalink
    def get_absolute_url(self):
        return 'core:autor', (), {'pk': self.pk}

    def delete(self, using=None):
        self.ativo = False
        self.save()

    def __unicode__(self):
        return self.nome


class Galeria(models.Model):
    ordenacao = models.PositiveSmallIntegerField(u'Ordenação', default=0)
    nome = models.CharField(max_length=120)
    desc = models.TextField(u'Descrição', blank=True)
    imagem = models.ImageField(upload_to='galeria')
    thumb = ImageSpecField(source='imagem', processors=[ResizeToFill(160, 160)], format='JPEG', options={'quality': 60})
    autor = models.ForeignKey(Autor, null=True, blank=True)
    ativo = models.BooleanField(default=False)

    data_criacao = models.DateTimeField(
        verbose_name=u'Data de criação',
        auto_now_add=True,
        editable=True
    )
    data_atualizacao = models.DateTimeField(
        verbose_name=u'Data de atualização',
        auto_now=True,
        editable=True
    )

    def codigo(self):
        return 'P{0:03d}'.format(self.pk)

    objects = AtivoManager()

    class Meta:
        ordering = ['ordenacao', 'nome']

    def delete(self, using=None):
        self.ativo = False
        self.save()

    def __unicode__(self):
        return self.nome


class Sugestao(models.Model):
    ordenacao = models.PositiveSmallIntegerField(u'Ordenação', default=0)
    titulo = models.CharField(u'Título', max_length=120)
    desc = models.TextField(u'Descrição', blank=True)
    link = models.URLField(blank=True)
    ativo = models.BooleanField(default=False)

    data_criacao = models.DateTimeField(
        verbose_name=u'Data de criação',
        auto_now_add=True,
        editable=True
    )
    data_atualizacao = models.DateTimeField(
        verbose_name=u'Data de atualização',
        auto_now=True,
        editable=True
    )

    objects = AtivoManager()

    class Meta:
        ordering = ['ordenacao', 'titulo']
        verbose_name = u'Sugestão'
        verbose_name_plural = u'Sugestões'

    def delete(self, using=None):
        self.ativo = False
        self.save()

    def __unicode__(self):
        return self.titulo

core/views.py
# coding: utf-8
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Galeria, Autor, Sugestao
from random import shuffle


class HomeListView(ListView):
    context_object_name = 'quadros'
    template_name = 'home.html'

    def get_queryset(self):
        qs = Galeria.objects.ativos()
        mix = list(qs)
        shuffle(mix)
        return mix


class GalleryRoomListView(ListView):
    context_object_name = 'quadros'
    template_name = 'gallery/index.html'

    def get_queryset(self):
        qs = Galeria.objects.ativos()
        mix = list(qs)
        shuffle(mix)
        return mix[:10]


class AutorListView(ListView):
    queryset = Autor.objects.ativos()
    context_object_name = 'autores'
    template_name = 'autores.html'


class AutorDetailView(DetailView):
    model = Autor
    context_object_name = 'autor'
    template_name = 'autor.html'


class GaleriaListView(ListView):
    context_object_name = 'quadros'
    template_name = 'galeria.html'

    def get_queryset(self):
        cod_quadro = self.request.GET.get('quadro', None)

        if cod_quadro:

            if cod_quadro[0] == 'p' or cod_quadro[0] == 'P' or cod_quadro.isdigit():
                if cod_quadro.isdigit():
                    cod_quadro = int(cod_quadro)
                elif cod_quadro.startswith('P'):
                    if cod_quadro == 'P':
                        cod_quadro = 0
                    else:
                        cod_quadro = int(cod_quadro.replace('P', ''))
                elif cod_quadro.startswith('p'):
                    if cod_quadro == 'p':
                        cod_quadro = 0
                    else:
                        cod_quadro = int(cod_quadro.replace('p', ''))
                else:
                    cod_quadro = 0
            else:
                cod_quadro = 0

            quadros = Galeria.objects.ativos().filter(pk=int(cod_quadro))

            if quadros:
                return quadros
            else:
                return []

        else:
            return Galeria.objects.ativos()


class SugestaoListView(ListView):
    queryset = Sugestao.objects.ativos()
    context_object_name = 'sugestoes'
    template_name = 'sugestoes.html'


class VenderTemplateView(TemplateView):
    template_name = 'vender.html'


class ComprarTemplateView(TemplateView):
    template_name = 'comprar.html'


class ContatoTemplateView(TemplateView):
    template_name = 'contato.html'

core/templates/autor.html
{% extends "base.html" %}

{% block extra_head %}
    <!-- fancybox -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/jquery.fancybox.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-buttons.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-thumbs.css" />
    <!-- Perfect Scroll Bar -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/perfect-scrollbar-0.4.1.min.css" />
{% endblock %}

{% block title %}Galeria{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1><i>{{ autor.nome }}</i></h1>
        </div>
        <div class="row">
            <div class="span5 quadro-imagem-sem-altura">
                {% if autor.imagem %}
                    <img width="160" height="160" src="{{ autor.thumb.url }}"
                        alt="{{ autor.nome }}" title="{{ autor.nome }}">
                {% else %}
                    <img width="160" height="160" src="{{ STATIC_URL }}img/autor-sem-foto.jpg"
                        alt="{{ autor.nome }}" title="{{ autor.nome }}">
                {% endif %}
                {% if autor.desc %}<div class="desc-autor">{{ autor.desc|linebreaks }}</div>{% endif %}
            </div>
            {% if autor.galeria_set.count %}
            <div class="span7">
                <ul class="thumbnails">
                    {% for quadro in autor.galeria_set.all %}
                        <li class="span2 quadro-imagem">
                            <a href="{{ quadro.imagem.url }}" class="thumb" title="{{ quadro.nome }}">
                                <img width="160" height="160" src="{{ quadro.thumb.url }}"
                                     alt="{{ quadro.nome }}" title="{{ quadro.nome }}">
                            </a>
                        </li>
                        <li class="span5 quadro-texto">
                            <h4>{{ quadro.nome }}</h4>
                            {% if quadro.desc %}{{ quadro.desc|linebreaks }}{% endif %}
                        </li>
                    {% empty %}
                        <li>Não há quadros cadastrados</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <!-- fancybox -->
    <script src="{{ STATIC_URL }}fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
    <!-- Add fancyBox main JS and CSS files -->
    <script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/jquery.fancybox.js"></script>
    <!-- Add Button helper (this is optional) -->
    <script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-buttons.js"></script>
    <!-- Add Thumbnail helper (this is optional) -->
    <script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-thumbs.js"></script>
    <!-- Add Media helper (this is optional) -->
    <script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-media.js"></script>
    <!-- Perfect Scroll Bar -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/perfect-scrollbar-0.4.1.min.js"></script>
<script>
    // Set custom style, close if clicked, change title type and overlay color
    $(".thumb").fancybox({
        wrapCSS    : 'fancybox-custom',
        closeClick : true,

        openEffect : 'none',

        helpers : {
            title : {
                type : 'inside'
            },
            overlay : {
                css : {
                    'background' : 'rgba(238,238,238,0.85)'
                }
            }
        }
    });
    $('.quadro-texto').perfectScrollbar({
        wheelSpeed: 20,
        wheelPropagation: false
    });
</script>
{% endblock %}

core/templates/autores.html
{% extends "base.html" %}

{% block extra_head %}
    <!-- Perfect Scroll Bar -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/perfect-scrollbar-0.4.1.min.css" />
{% endblock %}

{% block title %}Autores{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">

                <div class="page-header">
                    <h1>Autores</h1>
                </div>

                <ul class="thumbnails">
                    {% for autor in autores %}
                        <li class="span2 quadro-imagem">
                            {% if autor.imagem %}
                                <a href="{% url 'core:autor' autor.pk %}">
                                    <img width="160" height="160" src="{{ autor.thumb.url }}"
                                         alt="{{ autor.nome }}" title="{{ autor.nome }}">
                                </a>
                            {% else %}
                                <a href="{% url 'core:autor' autor.pk %}">
                                    <img width="160" height="160" src="{{ STATIC_URL }}img/autor-sem-foto.jpg"
                                         alt="{{ autor.nome }}" title="{{ autor.nome }}">
                                </a>
                            {% endif %}
                        </li>
                        <li class="span10 quadro-texto">
                            <h4><a href="{% url 'core:autor' autor.pk %}">{{ autor.nome }}</a></h4>
                            {% if autor.desc %}{{ autor.desc|linebreaks }}{% endif %}
                        </li>
                    {% empty %}
                        <li>Não há autores cadastrados</li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{{ STATIC_URL }}fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
    <!-- Perfect Scroll Bar -->
    <script type="text/javascript" src="{{ STATIC_URL }}js/perfect-scrollbar-0.4.1.min.js"></script>
<script>
    $('.quadro-texto').perfectScrollbar({
        wheelSpeed: 20,
        wheelPropagation: false
    });
</script>
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Pistalo | {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Google Web Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Vollkorn:400italic,700italic,400,700' rel='stylesheet' type='text/css'>

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Custom style -->
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
    <![endif]-->
    {% block extra_head %}{% endblock %}
</head>

<body>
<header>
    <div class="container">
        <div class="row">
            <div class="logo-pistalo">
                <a href="{% url 'core:home' %}">
                    <img src="{{ STATIC_URL }}img/logo-pistalo.png">
                </a>
            </div>
            <div class="span10">
                <div class="top-menu pull-right">
                    <a href="{% url 'core:galeria' %}">Comprar</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <a href="{% url 'core:autores' %}">Autores</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <a href="{% url 'core:sugestoes' %}">Sugestões</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <a href="{% url 'core:vender' %}">Publicar</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                    <a href="{% url 'core:contato' %}">Contato</a>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="main">
{% block content %}{% endblock %}
</div>
<footer>
    <div class="container">
        <span>&copy; 2013 <a href="{% url 'admin:index' %}">Pistalo</a></span>
        <span class="pull-right"><a id="page-top" href="#topo">Topo <i class="icon-arrow-up"></i></a></span>
    </div>
</footer>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
{% block scripts %}{% endblock %}
<script>
    $('#page-top').click(function () {
        $('body').animate({scrollTop: 0}, 'fast');
    });
</script>
</body>
</html>

core/templates/comprar.html
{% extends "base.html" %}

{% block title %}Comprar{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">

                <div class="page-header">
                    <h1>Comprar</h1>
                </div>

                <div class="row">

                    <div class="span3">
                        <strong>Dados:</strong>
                        <p>
                            Email:
                            <a href="mailto:pistalo@hotmail.com?subject=Comprar&body=Nome:%20%0D%0ATelefone:%20%0D%0AMensagem:%20%0D%0A">
                                pistalo@hotmail.com
                            </a><br>
                            Fone: (85) 9621-6921<br>
                            No título do email escreva <strong>"Comprar"</strong>.
                        </p>
                    </div>
                    <div class="span3">
                        <strong>Informe:</strong>
                        <ul>
                            <li>Nome</li>
                            <li>Telefone</li>
                            <li>Mensagem</li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

core/templates/contato.html
{% extends "base.html" %}

{% block title %}Contato{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">

                <div class="page-header">
                    <h1>Contato</h1>
                </div>

                <div class="row">

                    <div class="span3">
                        <strong>Dados:</strong>
                        <p>
                            Email:
                            <a href="mailto:pistalo@hotmail.com?subject=Contato&body=Nome:%20%0D%0ATelefone:%20%0D%0AMensagem:%20%0D%0A">
                                pistalo@hotmail.com
                            </a><br>
                            Fone: (85) 9621-6921<br>
                            No título do email escreva o assunto: Contato, Sugestão ou Elogio
                        </p>
                    </div>
                    <div class="span3">
                        <strong>Informe:</strong>
                        <ul>
                            <li>Nome</li>
                            <li>Telefone</li>
                            <li>Mensagem</li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/galeria.html
{% extends "core/base.html" %}
{% load thumbnail %}

{% block extra_head %}
    <!-- fancybox -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/jquery.fancybox.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-buttons.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-thumbs.css" />
{% endblock %}

{% block title %}Galeria{% endblock %}

{% block content %}

<div class="main">
    <div class="container">
        <div class="row">
            <div class="span12">

                <div class="page-header">
                    <h1>Galeria <small>Clique no quadro para ampliar</small></h1>
                </div>

                <ul class="thumbnails">
                    {% for quadro in quadros %}
                        <li class="span2" style="height: 160px">
                            <a href="{{ quadro.imagem.url }}" class="thumbnail" title="{{ quadro.nome }}">
                            {% thumbnail quadro.thumb "160x160" crop="center" as im %}
                                <img width="{{ im.width }}" height="{{ im.height }}" src="{{ im.url }}" alt="{{ quadro.nome }}" title="{{ quadro.nome }}">
                            {% endthumbnail %}
                            </a>
                        </li>
                        <li class="span4" style="height: 160px; overflow-y: auto">
                            <h4>{{ quadro.nome }}</h4>
                            {% if quadro.desc %}<p>{{ quadro.desc }}</p>{% endif %}
                        </li>
                    {% empty %}
                        <li>Não há quadros cadastrados</li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<!-- fancybox -->
<script src="{{ STATIC_URL }}fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
<!-- Add fancyBox main JS and CSS files -->
<script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/jquery.fancybox.js"></script>
<!-- Add Button helper (this is optional) -->
<script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-buttons.js"></script>
<!-- Add Thumbnail helper (this is optional) -->
<script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-thumbs.js"></script>
<!-- Add Media helper (this is optional) -->
<script type="text/javascript" src="{{ STATIC_URL }}fancybox/source/helpers/jquery.fancybox-media.js"></script>

<script>
    // Set custom style, close if clicked, change title type and overlay color
    $(".thumbnail").fancybox({
        wrapCSS    : 'fancybox-custom',
        closeClick : true,

        openEffect : 'none',

        helpers : {
            title : {
                type : 'inside'
            },
            overlay : {
                css : {
                    'background' : 'rgba(238,238,238,0.85)'
                }
            }
        }
    });
</script>
{% endblock %}

core/templates/gallery/base.html
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Pistalo Gallery Room</title>
		<meta name="description" content="Add a description" />
		<meta name="keywords" content="Add keywords" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}gallery/css/default.css" />
        {% block extra_head %}{% endblock %}
        <script src="{{ STATIC_URL }}gallery/js/modernizr.custom.js"></script>
	</head>
	<body>
		{% block content %}{% endblock %}
		<script src="{{ STATIC_URL }}gallery/js/jquery.min.js"></script>
		<script src="{{ STATIC_URL }}gallery/js/wallgallery.js"></script>
		<script>
			$(function() {
				Gallery.init( {
					layout : [3,2,3,2]
				} );

			});
		</script>
	</body>
</html>

core/templates/gallery/index.html
{% extends "gallery/base.html" %}
{% block title %}Pistalo - Gallery Room{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}gallery/css/component.css" />
    <script src="{{ STATIC_URL }}gallery/js/modernizr.custom.js"></script>
{% endblock %}
{% block content %}
    <div class="container">
        <!-- Codrops top bar -->
        <div class="codrops-top clearfix">
            <a href="{% url 'core:home' %}"><strong>Home</strong></a>
            <span class="right">
                <a href="{% url 'core:galeria' %}">Comprar</a>
                <a href="{% url 'core:autores' %}">Autores</a>
                <a href="{% url 'core:sugestoes' %}">Sugestões</a>
                <a href="{% url 'core:vender' %}">Publicar</a>
                <a href="{% url 'core:contato' %}">Contato</a>
            </span>
        </div><!--/ Codrops top bar -->

        <h1>&copy; 2013 <a href="{% url 'admin:index' %}">Pistalo</a></h1>

        <div id="gr-gallery" class="gr-gallery">
            <div class="gr-main">

                {% for quadro in quadros %}
                    <figure>
                        <div>
                            <img src="{{ quadro.imagem.url }}" alt="{{ quadro.nome }}" />
                        </div>
                        <figcaption>
                            <h2>
                                <a class="btn btn-mini btn-success"
                                   href="mailto:pistalo@hotmail.com?subject=Comprar&body=Nome:%20%0D%0ATelefone:%20%0D%0AQuadro:%20{{ quadro.nome }}%0D%0ACódigo:%20{{ quadro.codigo }}%0D%0AMensagem:%20%0D%0A">
                                    Comprar
                                </a>
                                <strong style="float: right; margin: 3px 3px">#{{ quadro.codigo }}</strong>
                            </h2>
                            <div>
                                {{ quadro.nome }} por
                                {% if quadro.autor %}
                                    <a href="{{ quadro.autor.get_absolute_url }}">{{ quadro.autor.nome }}</a>
                                {% endif %}
                            </div>
                            <div>
                                {% if quadro.desc %}{{ quadro.desc|linebreaks }}{% endif %}
                            </div>
                        </figcaption>
                    </figure>
                {% endfor %}

            </div>
        </div>
    </div><!-- /container -->
{% endblock %}

core/templates/home.html
{% extends "base.html" %}

{% block title %}Galeria{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="row">

                    <div class="span12">
                        <ul class="bxslider">
                            {% for quadro in quadros %}
                            <li><img src="{{ quadro.imagem.url }}" /></li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_head %}
    <link href="{{ STATIC_URL }}bxslider/jquery.bxslider.css" rel="stylesheet">
    <style>
    .bx-wrapper {
        margin-top: 20px;
        width: 50%;
    }
    .bx-wrapper .bx-viewport {
        background-color: rgba(255, 255, 255, .5);
        border: none;
        text-align: center;

        -webkit-border-radius: 6px;
        -moz-border-radius: 6px;
        border-radius: 6px;
    }
    ul.bxslider li img {
        width: 100%;

        -webkit-border-radius: 6px;
        -moz-border-radius: 6px;
        border-radius: 6px;
    }
    ul.bxslider { margin: 0 }
    @media (max-width: 767px) {
        .bx-wrapper {
            margin-top: 20px;
            width: 100%;
        }
    }
    </style>
{% endblock %}
{% block scripts %}
    <script src="{{ STATIC_URL }}bxslider/jquery.bxslider.min.js"></script>
    <script type="text/javascript">
        $('.bxslider').bxSlider({
            auto: true,
            autoControls: true,
            adaptiveHeight: true,
            mode: 'fade',
            speed: 500,
            randomStart: true
        });
    </script>
{% endblock %}

core/templates/sugestoes.html
{% extends "base.html" %}

{% block title %}Sugestões{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">

                <div class="page-header">
                    <h1>Sugestões</h1>
                </div>

                <ul>
                    {% for sugestao in sugestoes %}
                        <li style="height: auto">
                            <h4>
                                {% if sugestao.link %}<a href="{{ sugestao.link }}" target="_blank">{% endif %}
                                    {{ sugestao.titulo }}
                                {% if sugestao.link %}</a>{% endif %}
                            </h4>
                            {% if sugestao.desc %}<blockquote>{{ sugestao.desc|linebreaks }}</blockquote>{% endif %}
                        </li>
                    {% empty %}
                        <li>Não há sugestões cadastradas</li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
{% endblock %}